import { Fonts, ThemeColors } from "@/constants/theme";
import { Platform, StatusBar, StyleSheet } from "react-native";

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    backgroundColor: ThemeColors.background,
  },
  content: {
    flex: 1,
  },
  messagesList: {
    paddingVertical: 16,
  },
});

export const chatHeaderStyles = StyleSheet.create({
  container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    backgroundColor: ThemeColors.background,
    borderBottomColor: ThemeColors.borderLight,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: ThemeColors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 17,
    color: ThemeColors.text,
  },
});

export const emptyChatStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 80,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 40,
  },
  iconWrapper: {
    marginBottom: 24,
  },
  iconBg: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: ThemeColors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 26,
    color: ThemeColors.text,
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.textSecondary,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 32,
  },
  suggestions: {
    width: "100%",
    gap: 10,
  },
  suggestionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: ThemeColors.surface,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  suggestionText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 14,
    color: ThemeColors.text,
    flex: 1,
  },
});

export const chatBubbleStyles = StyleSheet.create({
  container: {
    gap: 10,
    marginBottom: 16,
    flexDirection: "row",
    paddingHorizontal: 10,
    alignItems: "flex-end",
  },
  containerUser: {
    justifyContent: "flex-end",
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ThemeColors.primary,
  },
  avatarUser: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ThemeColors.text,
  },
  bubble: {
    maxWidth: "75%",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 18,
  },
  bubbleAI: {
    backgroundColor: ThemeColors.surface,
    borderWidth: 1,
    borderColor: ThemeColors.borderLight,
    borderBottomLeftRadius: 4,
  },
  bubbleUser: {
    backgroundColor: ThemeColors.text,
    borderBottomRightRadius: 4,
  },
  text: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.text,
    lineHeight: 22,
  },
  textUser: {
    color: ThemeColors.surface,
  },
});

export const chatInputStyles = StyleSheet.create({
  container: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: ThemeColors.background,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: ThemeColors.surface,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: ThemeColors.border,
    paddingLeft: 16,
    paddingRight: 8,
    paddingVertical: 8,
    gap: 8,
  },
  inputWrapperFocused: {
    borderColor: ThemeColors.primary,
  },
  input: {
    flex: 1,
    fontFamily: Fonts.brand,
    fontSize: 16,
    color: ThemeColors.text,
    paddingHorizontal: 4,
    paddingVertical: 10,
    maxHeight: 120,
    minHeight: 44,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: ThemeColors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  sendButtonActive: {
    backgroundColor: ThemeColors.text,
  },
});

export const transactionApprovalModalStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 1000,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  sheet: {
    backgroundColor: ThemeColors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    maxHeight: "90%",
    flexDirection: "column",
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 16,
  },
  handleContainer: {
    alignItems: "center",
    paddingVertical: 12,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: ThemeColors.border,
  },
  header: {
    alignItems: "center",
    marginBottom: 28,
  },
  headerIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: ThemeColors.primary + "50",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 24,
    color: ThemeColors.text,
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textMuted,
    textAlign: "center",
  },
  detailsContainer: {
    gap: 16,
  },
  // Amount Section - Large and Prominent
  amountSection: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: ThemeColors.borderLight,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  amountLabel: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  amountValue: {
    fontFamily: Fonts.brandBold,
    fontSize: 40,
    color: ThemeColors.text,
    marginBottom: 12,
  },
  feeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: ThemeColors.background,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  feeText: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
  },
  // Recipient Card
  recipientCard: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: ThemeColors.borderLight,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  recipientHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: ThemeColors.borderLight,
  },
  recipientIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ThemeColors.primary + "30",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionLabel: {
    fontFamily: Fonts.brandBold,
    fontSize: 15,
    color: ThemeColors.text,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  recipientContent: {
    gap: 12,
  },
  recipientName: {
    fontFamily: Fonts.brandBold,
    fontSize: 18,
    color: ThemeColors.text,
  },
  addressContainer: {
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  recipientAddress: {
    fontFamily: Fonts.brandMedium,
    fontSize: 16,
    color: ThemeColors.text,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  networkWarningContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: ThemeColors.primary + "20",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ThemeColors.primaryDark + "50",
    marginTop: 4,
  },
  networkInfo: {
    fontFamily: Fonts.brandBold,
    fontSize: 15,
    color: ThemeColors.primaryDark,
    flex: 1,
  },
  // Network Badge
  networkBadge: {
    backgroundColor: ThemeColors.surface,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  networkText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.textSecondary,
  },
  // Summary Card
  summaryCard: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 16,
    padding: 20,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: ThemeColors.borderLight,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  summaryLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  summaryLabel: {
    fontFamily: Fonts.brandBold,
    fontSize: 16,
    color: ThemeColors.textSecondary,
  },
  summaryValue: {
    fontFamily: Fonts.brandBold,
    fontSize: 20,
    color: ThemeColors.text,
  },
  completionContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: ThemeColors.borderLight,
  },
  completionTime: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
  },
  actionsContainer: {
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: ThemeColors.borderLight,
    backgroundColor: ThemeColors.surface,
  },
  rejectButton: {
    paddingVertical: 16,
    alignItems: "center",
  },
  rejectText: {
    fontFamily: Fonts.brand,
    fontSize: 16,
    color: ThemeColors.textSecondary,
  },
});

export const transactionResultModalStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 1000,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  sheet: {
    backgroundColor: ThemeColors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    maxHeight: "90%",
  },
  handleContainer: {
    alignItems: "center",
    paddingVertical: 12,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: ThemeColors.border,
  },
  header: {
    alignItems: "center",
    marginBottom: 24,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  iconContainerSuccess: {
    backgroundColor: `${ThemeColors.success}15`,
  },
  iconContainerError: {
    backgroundColor: `${ThemeColors.error}15`,
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 22,
    color: ThemeColors.text,
    textAlign: "center",
  },
  content: {
    alignItems: "center",
    marginBottom: 24,
  },
  successMessage: {
    fontFamily: Fonts.brandBold,
    fontSize: 18,
    color: ThemeColors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  completionTime: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
    marginBottom: 16,
    textAlign: "center",
  },
  transactionIdContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    width: "100%",
    gap: 8,
  },
  transactionIdLabel: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
  },
  transactionId: {
    flex: 1,
    fontFamily: Fonts.brandMedium,
    fontSize: 13,
    color: ThemeColors.text,
  },
  networkBadge: {
    backgroundColor: ThemeColors.background,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 16,
  },
  networkText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.textSecondary,
  },
  reassuringMessage: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
    textAlign: "center",
  },
  failureMessage: {
    fontFamily: Fonts.brandBold,
    fontSize: 18,
    color: ThemeColors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  errorReason: {
    fontFamily: Fonts.brandMedium,
    fontSize: 15,
    color: ThemeColors.error,
    marginBottom: 16,
    textAlign: "center",
  },
  attemptedMessage: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
    marginBottom: 16,
    textAlign: "center",
  },
  reassuranceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    gap: 12,
    width: "100%",
  },
  reassuranceText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 15,
    color: ThemeColors.text,
    flex: 1,
  },
  errorCode: {
    fontFamily: Fonts.brand,
    fontSize: 12,
    color: ThemeColors.textMuted,
    textAlign: "center",
  },
  actionsContainer: {
    gap: 12,
  },
  secondaryButton: {
    paddingVertical: 16,
    alignItems: "center",
  },
  secondaryButtonText: {
    fontFamily: Fonts.brand,
    fontSize: 16,
    color: ThemeColors.textSecondary,
  },
  saveAddressCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    width: "100%",
    borderWidth: 1,
    borderColor: ThemeColors.borderLight,
  },
  saveAddressHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  saveAddressTitle: {
    fontFamily: Fonts.brandBold,
    fontSize: 16,
    color: ThemeColors.text,
  },
  saveAddressDescription: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textSecondary,
    marginBottom: 12,
  },
  saveAddressInputContainer: {
    marginBottom: 12,
  },
  saveAddressInput: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.text,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  saveAddressActions: {
    flexDirection: "row",
    gap: 12,
  },
  saveAddressCancelButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: ThemeColors.surface,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  saveAddressCancelText: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.textSecondary,
  },
  saveAddressSaveButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: ThemeColors.primary,
  },
  saveAddressSaveButtonDisabled: {
    opacity: 0.5,
  },
  saveAddressSaveText: {
    fontFamily: Fonts.brandBold,
    fontSize: 15,
    color: ThemeColors.text,
  },
  saveAddressSaveTextDisabled: {
    color: ThemeColors.textMuted,
  },
});

export const transactionFlowModalStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  sheet: {
    backgroundColor: ThemeColors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    maxHeight: "85%",
    minHeight: 200,
  },
  handle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: ThemeColors.border,
    marginBottom: 16,
  },
  contentContainer: {
    flexGrow: 1,
    columnGap: 16,
    flexShrink: 0,
    paddingBottom: 130,
  },
  // Approval styles
  header: {
    alignItems: "center",
    marginBottom: 20,
  },
  headerIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: `${ThemeColors.primary}30`,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 22,
    color: ThemeColors.text,
  },
  subtitle: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textMuted,
    marginTop: 4,
  },
  amountCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 16,
  },
  amountLabel: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.textMuted,
    letterSpacing: 1,
    marginBottom: 8,
  },
  amountValue: {
    fontFamily: Fonts.brandBold,
    fontSize: 36,
    color: ThemeColors.text,
  },
  feeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 8,
  },
  feeText: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
  },
  recipientCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  recipientHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  recipientIconBg: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: `${ThemeColors.primary}30`,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontFamily: Fonts.brandBold,
    fontSize: 14,
    color: ThemeColors.text,
  },
  recipientName: {
    fontFamily: Fonts.brandBold,
    fontSize: 16,
    color: ThemeColors.text,
    marginBottom: 8,
  },
  addressBox: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  addressText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 13,
    color: ThemeColors.text,
    lineHeight: 20,
  },
  networkBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: `${ThemeColors.primary}15`,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  networkText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.primaryDark,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: ThemeColors.borderLight,
    marginBottom: 8,
  },
  totalLabel: {
    fontFamily: Fonts.brandBold,
    fontSize: 16,
    color: ThemeColors.textSecondary,
  },
  totalValue: {
    fontFamily: Fonts.brandBold,
    fontSize: 20,
    color: ThemeColors.text,
  },
  actions: {
    gap: 8,
    paddingTop: 8,
  },
  cancelBtn: {
    paddingVertical: 14,
    alignItems: "center",
  },
  cancelText: {
    fontFamily: Fonts.brand,
    fontSize: 16,
    color: ThemeColors.textSecondary,
  },
  // Processing styles
  processingContent: {
    alignItems: "center",
    paddingVertical: 20,
  },
  spinnerContainer: {
    marginBottom: 24,
  },
  spinner: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 3,
    borderColor: ThemeColors.primary,
    borderTopColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  spinnerInner: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: ThemeColors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  completedIcon: {
    width: 72,
    height: 72,
    justifyContent: "center",
    alignItems: "center",
  },
  statusText: {
    fontFamily: Fonts.brandBold,
    fontSize: 18,
    color: ThemeColors.text,
    marginBottom: 20,
  },
  infoCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginBottom: 24,
    width: "100%",
  },
  infoAmount: {
    fontFamily: Fonts.brandBold,
    fontSize: 24,
    color: ThemeColors.text,
  },
  infoRecipient: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
    marginTop: 4,
  },
  stepsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  stepItem: {
    alignItems: "center",
  },
  stepDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ThemeColors.background,
    borderWidth: 2,
    borderColor: ThemeColors.border,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  stepDotActive: {
    borderColor: ThemeColors.primary,
    backgroundColor: `${ThemeColors.primary}15`,
  },
  stepDotDone: {
    backgroundColor: ThemeColors.success,
    borderColor: ThemeColors.success,
  },
  stepLabel: {
    fontFamily: Fonts.brand,
    fontSize: 12,
    color: ThemeColors.textMuted,
  },
  stepLabelActive: {
    fontFamily: Fonts.brandMedium,
    color: ThemeColors.text,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: ThemeColors.border,
    marginHorizontal: 4,
    marginBottom: 20,
  },
  stepLineActive: {
    backgroundColor: ThemeColors.success,
  },
  // Result styles
  resultContent: {
    alignItems: "center",
    paddingVertical: 16,
  },
  resultIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  resultIconSuccess: {
    backgroundColor: `${ThemeColors.success}15`,
  },
  resultIconError: {
    backgroundColor: `${ThemeColors.error}15`,
  },
  resultTitle: {
    fontFamily: Fonts.brandBold,
    fontSize: 22,
    color: ThemeColors.text,
    marginBottom: 8,
  },
  resultMessage: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.textSecondary,
    textAlign: "center",
    marginBottom: 16,
  },
  txIdRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ThemeColors.background,
    borderRadius: 10,
    padding: 12,
    width: "100%",
    gap: 8,
    marginBottom: 16,
  },
  txIdLabel: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.textMuted,
  },
  txId: {
    flex: 1,
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.text,
  },
  errorMessage: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.error,
    textAlign: "center",
    marginBottom: 16,
  },
  safeCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: ThemeColors.background,
    borderRadius: 10,
    padding: 14,
    width: "100%",
  },
  safeText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 14,
    color: ThemeColors.text,
  },
  // Save address
  saveCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 12,
    padding: 14,
    width: "100%",
  },
  saveHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  saveTitle: {
    fontFamily: Fonts.brandBold,
    fontSize: 15,
    color: ThemeColors.text,
  },
  saveInput: {
    backgroundColor: ThemeColors.surface,
    borderRadius: 8,
    padding: 12,
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.text,
    borderWidth: 1,
    borderColor: ThemeColors.border,
    marginBottom: 10,
  },
  saveActions: {
    flexDirection: "row",
    gap: 10,
  },
  saveSkip: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: ThemeColors.border,
  },
  saveSkipText: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
  },
  saveSaveBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: ThemeColors.primary,
  },
  saveSaveText: {
    fontFamily: Fonts.brandBold,
    fontSize: 14,
    color: ThemeColors.text,
  },
});
