import { Fonts, ThemeColors } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const transactionProcessingModalStyles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    zIndex: 1000,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  sheet: {
    backgroundColor: ThemeColors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 8,
    maxHeight: "90%",
    minHeight: 0,
  },
  handleContainer: {
    alignItems: "center",
    paddingVertical: 12,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: ThemeColors.border,
  },
  header: {
    alignItems: "center",
    marginBottom: 32,
  },
  title: {
    fontFamily: Fonts.brandBold,
    fontSize: 22,
    color: ThemeColors.text,
    textAlign: "center",
    flexShrink: 1,
    paddingHorizontal: 8,
  },
  content: {
    alignItems: "center",
    marginBottom: 24,
  },
  progressContainer: {
    marginBottom: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  spinnerWrapper: {
    width: 80,
    height: 80,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  pulseRing: {
    position: "absolute",
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: ThemeColors.primary,
  },
  spinnerRing: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: ThemeColors.primary,
    borderTopColor: "transparent",
    borderRightColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  spinnerInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: ThemeColors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  statusMessage: {
    fontFamily: Fonts.brandBold,
    fontSize: 18,
    color: ThemeColors.text,
    marginBottom: 24,
    textAlign: "center",
    flexShrink: 1,
    paddingHorizontal: 8,
  },
  infoCard: {
    backgroundColor: ThemeColors.background,
    borderRadius: 16,
    padding: 20,
    width: "100%",
    marginBottom: 20,
    alignItems: "center",
    minHeight: 0,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  infoLabel: {
    fontFamily: Fonts.brandMedium,
    fontSize: 13,
    color: ThemeColors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoValue: {
    fontFamily: Fonts.brandBold,
    fontSize: 24,
    color: ThemeColors.text,
    marginBottom: 4,
    flexShrink: 1,
    textAlign: "center",
  },
  infoRecipient: {
    fontFamily: Fonts.brand,
    fontSize: 14,
    color: ThemeColors.textSecondary,
    flexShrink: 1,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  networkBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: ThemeColors.background,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 32,
    gap: 8,
  },
  networkDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: ThemeColors.primary,
  },
  networkText: {
    fontFamily: Fonts.brandMedium,
    fontSize: 12,
    color: ThemeColors.textSecondary,
    flexShrink: 1,
  },
  stagesContainer: {
    width: "100%",
    marginBottom: 24,
  },
  stageItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  stageIndicator: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: ThemeColors.background,
    borderWidth: 2,
    borderColor: ThemeColors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  stageIndicatorActive: {
    borderColor: ThemeColors.primary,
    backgroundColor: `${ThemeColors.primary}15`,
  },
  stageIndicatorCompleted: {
    backgroundColor: ThemeColors.success,
    borderColor: ThemeColors.success,
  },
  stageLabel: {
    fontFamily: Fonts.brand,
    fontSize: 15,
    color: ThemeColors.textMuted,
    flex: 1,
    flexShrink: 1,
  },
  stageLabelActive: {
    fontFamily: Fonts.brandMedium,
    color: ThemeColors.text,
  },
  stageConnector: {
    width: 2,
    height: 20,
    backgroundColor: ThemeColors.border,
    marginLeft: 19,
    marginVertical: 4,
  },
  stageConnectorActive: {
    backgroundColor: ThemeColors.primary,
  },
  estimatedTime: {
    fontFamily: Fonts.brand,
    fontSize: 13,
    color: ThemeColors.textMuted,
    textAlign: "center",
    flexShrink: 1,
    paddingHorizontal: 8,
  },
});
